# Generated by Django 2.2.5 on 2019-09-29 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('permissao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('patrocinio', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('local', models.IntegerField(default=0)),
                ('capacidade', models.IntegerField(default=0)),
                ('recursos_fixos', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(verbose_name='Data da Reserva')),
                ('data_inicio', models.DateTimeField(verbose_name='Hora Início')),
                ('data_final', models.DateTimeField(verbose_name='Hora Fim')),
                ('recursos_necessarios', models.CharField(max_length=2000)),
                ('aprovacao', models.BooleanField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djreservas.Grupo')),
                ('responsavel_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djreservas.Cliente')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djreservas.Sala')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djreservas.Grupo'),
        ),
    ]
