# Generated by Django 2.2.5 on 2019-10-08 01:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djreservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='data_final',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_fim',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Hora Fim'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Hora Início'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateField(verbose_name='Data da Reserva'),
        ),
        migrations.CreateModel(
            name='ReservasTeste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Data/Hora Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data/Hora Fim')),
                ('recursos_necessarios', models.CharField(max_length=2000)),
                ('aprovacao', models.BooleanField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djreservas.Grupo')),
                ('responsavel_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djreservas.Cliente')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djreservas.Sala')),
            ],
        ),
    ]
