# Generated by Django 2.2.5 on 2019-10-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djreservas', '0002_auto_20191007_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='recursos_necessarios',
            new_name='motivo',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='local',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='aprovacao',
            field=models.BooleanField(verbose_name='Aprovação'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='capacidade',
            field=models.IntegerField(default=0, verbose_name='Capacidade de Pessoas'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome da Sala'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='recursos_fixos',
            field=models.CharField(max_length=2000, verbose_name='Recursos Fixos'),
        ),
        migrations.DeleteModel(
            name='ReservasTeste',
        ),
    ]
