# Generated by Django 2.2.5 on 2019-10-17 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djreservas', '0003_auto_20191012_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='grupo',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='responsavel_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
