# Generated by Django 2.2.5 on 2019-10-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djreservas', '0004_auto_20191016_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='aprovacao',
            field=models.BooleanField(null=True, verbose_name='Aprovação'),
        ),
    ]
