# Generated by Django 2.2.5 on 2019-11-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djreservas', '0005_auto_20191016_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='cor',
            field=models.CharField(choices=[('red', 'vermelho'), ('blue', 'azul')], default='blue', max_length=20),
        ),
    ]
