# Generated by Django 2.2.5 on 2019-11-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djreservas', '0006_sala_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='cor',
            field=models.CharField(choices=[('red', 'Vermelho'), ('blue', 'Azul'), ('green', 'Verde'), ('orange', 'Laranja')], default='blue', max_length=20),
        ),
    ]
