# Generated by Django 2.2.5 on 2019-11-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djreservas', '0007_auto_20191104_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='motivo',
        ),
    ]
