# Generated by Django 2.2.5 on 2019-11-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djreservas', '0009_reserva_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='motivo',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
