# Generated by Django 2.2.5 on 2019-11-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djreservas', '0011_auto_20191105_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='motivo',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
