# Generated by Django 2.2.5 on 2019-11-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djreservas', '0014_auto_20191105_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='motivo',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
