# Generated by Django 2.2.5 on 2019-11-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djreservas', '0015_auto_20191106_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='motivo',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
