# Generated by Django 2.2.5 on 2019-11-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djreservas', '0016_auto_20191106_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='cor',
            field=models.CharField(choices=[('red', 'Vermelho'), ('blue', 'Azul'), ('green', 'Verde'), ('yellow', 'Amarelo'), ('orange', 'Laranja'), ('purple', 'Roxo')], default='blue', max_length=20),
        ),
    ]
